FROM node:20

WORKDIR /app

RUN npm cache clean --force
COPY package*.json ./

RUN rm -rf node_modules package-lock.json
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]